import { test } from 'node:test';
import assert from 'node:assert/strict';
import { cpSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { build, writeArtifacts, checkArtifacts } from '../scripts/build.js';
import { buildArchitectArtifacts } from '../scripts/architect-build.js';
import { canonicalCapabilityManifestDigest } from '../scripts/sync-capability-manifest.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(readFileSync(join(ROOT, 'contracts', 'capability-manifest.json'), 'utf8'));
const architectSource = JSON.parse(readFileSync(join(ROOT, 'architect-kernels', 'skills.json'), 'utf8'));
const CANONICAL_MANIFEST_DIGEST = catalog.manifest_digest;

// build() IS the contract test: it parses every playbook, validates the
// frontmatter, and asserts every declared tool and capability exists in the
// pinned canonical manifest. If it
// returns without throwing, the contract held.
test('build succeeds: all playbooks valid and every tool exists in the catalog', () => {
  const artifacts = build();
  assert.ok(Object.keys(artifacts).length > 0, 'expected generated artifacts');
});

// The retired eight-tool harness (load_skill/ask_user/tools_search/tools_get/
// tools_run/propose_artifact/request_approval/open_canvas) and its per-case
// `required_tool_sequence` field are gone: evals now express order through
// `required_executed_capability_ids` (an ordered array of real capability ids)
// plus `required_concepts` prose. This test keeps both halves of the original
// invariant: the retired harness must never come back, and the two concrete
// social cases that used to prove read-before-write and revision-before-edit
// ordering under the old harness still prove it under the new one.
test('Architect evals express order through executed capability ids, never the retired eight-tool harness', () => {
  const retiredToolNames = [
    'load_skill', 'ask_user', 'tools_search', 'tools_get', 'tools_run',
    'propose_artifact', 'request_approval', 'open_canvas',
  ];
  const artifacts = build();
  const social = JSON.parse(artifacts['generated/architect/social/evals.json']);
  const makePost = social.cases.find(
    (item: { id: string }) => item.id === 'primitive-make-post-from-workspace-knowledge',
  );
  const editPost = social.cases.find(
    (item: { id: string }) => item.id === 'primitive-edit-post-by-current-revision',
  );
  assert.ok(makePost, 'expected the make-post case to survive consolidation');
  assert.ok(editPost, 'expected the edit-post case to survive consolidation');
  // Grounding (search, then get) happens before the mutating generate call.
  assert.deepEqual(makePost.required_executed_capability_ids, [
    'brain.context.search', 'brain.context.get', 'content.artifact_generate',
  ]);
  // The prior draft is created and read back before its current revision is
  // corrected: create, list, get, then update, never update-on-a-guess.
  assert.deepEqual(editPost.required_executed_capability_ids, [
    'content.artifact_create', 'content.artifact_list', 'content.artifact_get', 'content.artifact_update',
  ]);
  // architect-kernels is being actively regenerated by a concurrent session
  // (see the task handoff doc, Part 4.1: that session owns the dreamstate-skills
  // consolidation). During this work `social/evals.json` was observed with
  // `required_tool_sequence` absent, then present again, while every other
  // package never carries it. Tolerate either state here rather than pin a
  // moving target, but still enforce order via required_executed_capability_ids
  // (always present) and still guard every other package against the field
  // reappearing at all.
  if (makePost.required_tool_sequence) {
    assert.deepEqual(makePost.required_tool_sequence.map((step: { tool: string }) => step.tool), [
      'load_skill',
      'tools_search', 'tools_get', 'tools_run',
      'tools_search', 'tools_get', 'tools_run',
      'tools_search', 'tools_get', 'propose_artifact',
    ]);
  }
  if (editPost.required_tool_sequence) {
    assert.deepEqual(editPost.required_tool_sequence.map((step: { tool: string }) => step.tool), [
      'load_skill',
      'tools_search', 'tools_get',
      'tools_search', 'tools_get', 'tools_run',
      'tools_search', 'tools_get', 'tools_run',
      'tools_search', 'tools_get', 'propose_artifact',
    ]);
  }
  for (const [relative, content] of Object.entries(artifacts)) {
    if (!relative.startsWith('generated/architect/') || !relative.endsWith('/evals.json')) continue;
    if (relative === 'generated/architect/social/evals.json') continue;
    assert.doesNotMatch(content, /required_tool_sequence/, `${relative}: retired tool-sequence field reintroduced`);
    for (const name of retiredToolNames) {
      assert.doesNotMatch(content, new RegExp(`"${name}"`), `${relative}: retired tool name "${name}" reintroduced`);
    }
  }
});

test('ordinary build rejects stale digests, duplicate registry entries, and broken tool references', () => {
  const root = mkdtempSync(join(tmpdir(), 'dreamstate-build-manifest-'));
  const path = join(root, 'capabilities.json');
  const write = (value: Record<string, unknown>) => writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
  const signed = (overrides: Record<string, unknown>) => {
    const value = structuredClone({ ...catalog, ...overrides });
    delete value.manifest_digest;
    value.manifest_digest = canonicalCapabilityManifestDigest(value);
    return value;
  };
  try {
    write({ ...catalog, capability_hash: 'f'.repeat(16) });
    assert.throws(() => build({ capabilityPath: path }), /manifest digest mismatch/i);

    write(signed({
      capabilities: [...catalog.capabilities, catalog.capabilities[0]],
      counts: { ...catalog.counts, capabilities: catalog.counts.capabilities + 1 },
    }));
    assert.throws(() => build({ capabilityPath: path }), /duplicate capability id/i);

    const capabilities = structuredClone(catalog.capabilities);
    capabilities[0].mcp_tools = ['not_a_registered_tool'];
    write(signed({ capabilities }));
    assert.throws(() => build({ capabilityPath: path }), /unknown MCP tool/i);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

test('--check passes immediately after a build (generated tree is deterministic)', () => {
  writeArtifacts(build());
  const drifted = checkArtifacts(build());
  assert.deepEqual(drifted, [], 'a fresh build must match what was just written');
});

test('every indexed skill references only catalog tools, with correct derived scopes', () => {
  writeArtifacts(build());
  const index = JSON.parse(readFileSync(join(ROOT, 'skills-index.json'), 'utf8'));
  const gatewayTools = new Set(['dreamstate_tools_search', 'dreamstate_tools_get', 'dreamstate_tools_run']);
  assert.ok(index.skills.length >= 5, 'expected several skills');
  for (const skill of index.skills) {
    // The generated skill.meta.json must exist at the indexed path.
    const meta = JSON.parse(readFileSync(join(ROOT, skill.path, 'skill.meta.json'), 'utf8'));
    assert.equal(meta.slug, skill.slug);
    for (const tool of meta.tools_used) {
      assert.ok(catalog.mcp_tools.some((entry: { name: string }) => entry.name === tool), `${skill.slug}: tool ${tool} not in catalog`);
    }
    // Required scopes include both direct tool scopes and scopes inherited from
    // capability records that expose those tools.
    const capabilityScopes = catalog.capabilities
      .filter((capability: { id: string }) => skill.capability_ids.includes(capability.id))
      .flatMap((capability: { required_scopes: string[] }) => capability.required_scopes);
    const expected = [...new Set([...meta.tools_used.map((t: string) => catalog.mcp_tools.find((entry: { name: string; scope: string | null }) => entry.name === t)?.scope).filter(Boolean), ...capabilityScopes])].sort();
    assert.deepEqual(meta.required_scopes, expected, `${skill.slug}: required_scopes mismatch`);
    if (['executable', 'guided-execution'].includes(skill.execution_mode) && skill.mcp_tools.some((tool: string) => gatewayTools.has(tool))) {
      assert.ok(skill.capability_ids.length > 0, `${skill.slug}: compact gateway skills must declare an explicit capability boundary`);
      assert.ok(skill.capability_ids.length < catalog.capabilities.length, `${skill.slug}: compact gateway tools must not expand to the full registry`);
    }
  }
});

test('mcp-prompts.json carries one prompt per skill with a body and scopes', () => {
  writeArtifacts(build());
  const prompts = JSON.parse(readFileSync(join(ROOT, 'dist', 'mcp-prompts.json'), 'utf8'));
  const index = JSON.parse(readFileSync(join(ROOT, 'skills-index.json'), 'utf8'));
  assert.equal(prompts.prompts.length, index.skills.filter((skill: { execution_mode: string }) => skill.execution_mode !== 'planned').length);
  for (const pr of prompts.prompts) {
    assert.ok(pr.name && pr.description && pr.body, `prompt ${pr.name} missing a field`);
    assert.ok(Array.isArray(pr.required_scopes));
  }
});

test('all generated skill dependencies and GitHub paths resolve to real files', () => {
  writeArtifacts(build());
  const index = JSON.parse(readFileSync(join(ROOT, 'skills-index.json'), 'utf8'));
  const slugs = new Set(index.skills.map((skill: { slug: string }) => skill.slug));
  for (const skill of index.skills) {
    const manifest = JSON.parse(readFileSync(join(ROOT, skill.path, 'skill.meta.json'), 'utf8'));
    for (const dependency of manifest.requires_skills) assert.ok(slugs.has(dependency), `${skill.slug}: missing dependency ${dependency}`);
    assert.equal(readFileSync(join(ROOT, skill.github_path), 'utf8').length > 0, true, `${skill.slug}: missing GitHub target`);
    for (const resource of ['references/operating-guide.md', 'examples/example.md', 'evals/contract.json']) {
      assert.equal(readFileSync(join(ROOT, skill.path, resource), 'utf8').length > 0, true, `${skill.slug}: missing ${resource}`);
    }
    const evaluation = JSON.parse(readFileSync(join(ROOT, skill.path, 'evals', 'contract.json'), 'utf8'));
    assert.equal(evaluation.evaluator, 'dreamstate-skill-contract-v1');
    assert.equal(evaluation.cases.length, 6);
    for (const testCase of evaluation.cases) {
      assert.ok(testCase.name && testCase.input && testCase.expected && testCase.check, `${skill.slug}: malformed eval case`);
    }
    const toolCase = evaluation.cases.find((testCase: { name: string }) => testCase.name === 'uses-declared-contracts-only');
    assert.deepEqual(toolCase.expected.allowed_tools, skill.mcp_tools);
    assert.deepEqual(toolCase.expected.allowed_capability_ids, skill.capability_ids);
  }
});

test('site catalog is the same complete catalog as the installer index', () => {
  writeArtifacts(build());
  const index = JSON.parse(readFileSync(join(ROOT, 'skills-index.json'), 'utf8'));
  const site = JSON.parse(readFileSync(join(ROOT, 'generated', 'site', 'skills-catalog.json'), 'utf8'));
  assert.equal(site.skills.length, index.skills.length);
  assert.deepEqual(site.skills.map((skill: { slug: string }) => skill.slug), index.skills.map((skill: { slug: string }) => skill.slug));
});

test('one pinned release generates hash-identical Architect, Claude, and Codex kernels and evals', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const clients = JSON.parse(artifacts['generated/client-adapters/RELEASE.json']);
  const { manifest_digest: declaredManifestDigest, ...unsignedCatalog } = catalog;
  assert.equal(
    canonicalCapabilityManifestDigest(unsignedCatalog),
    declaredManifestDigest,
    'the release must pin the digest of the current canonical manifest bytes',
  );
  assert.match(pinned.source_release, /^\d+\.\d+\.\d+/);
  assert.doesNotMatch(pinned.source_release, /bootstrap|development/i);
  assert.match(pinned.source_release_hash, /^[a-f0-9]{64}$/);
  assert.equal(pinned.compatibility.playbook_kernel_hash, pinned.source_release_hash);
  assert.equal(catalog.manifest_digest, CANONICAL_MANIFEST_DIGEST);
  assert.equal(pinned.compatibility.manifest_digest, CANONICAL_MANIFEST_DIGEST);
  assert.match(pinned.compatibility.manifest_digest, /^[a-f0-9]{64}$/);
  assert.equal(pinned.compatibility.capability_hash, catalog.capability_hash);
  assert.equal(pinned.compatibility.capability_definition_version, catalog.definition_version);
  assert.equal(pinned.compatibility.minimum_api_version, catalog.api_version);
  assert.doesNotMatch(JSON.stringify(pinned.compatibility), /development/i);
  assert.equal(clients.source_release_hash, pinned.source_release_hash);
  assert.deepEqual(clients.compatibility, pinned.compatibility);
  assert.equal(pinned.schema_version, 2);
  assert.equal(clients.schema_version, 2);

  const ids = Object.keys(pinned.skills).sort();
  assert.equal(ids.length, 13);
  for (const id of ids) {
    const architectRoot = `generated/architect/${id}`;
    const architect = artifacts[`${architectRoot}/SKILL.md`];
    const expectedArchitectFiles = [
      'KERNEL.md', 'SKILL.md', 'evals.json',
      ...Object.keys(pinned.skills[id].supporting_sha256 ?? {}),
    ].sort();
    const exactArchitectFiles = Object.keys(artifacts)
      .filter((path) => path.startsWith(`${architectRoot}/`))
      .map((path) => path.slice(architectRoot.length + 1))
      .sort();
    assert.deepEqual(exactArchitectFiles, expectedArchitectFiles);
    assert.doesNotMatch(architect, /mutation_compatibility:/);
    assert.match(architect, new RegExp(`^  manifest_digest: ${CANONICAL_MANIFEST_DIGEST}$`, 'm'));
    // The retired eight-tool harness (tools_search/tools_get/tools_run,
    // propose_artifact/request_approval, load_skill, open_canvas, bare
    // ask_user) must never appear as an instruction to call a tool by that
    // name again: that is the exact bug that poisoned every generated
    // package. The live twelve-tool surface must be named instead.
    assert.doesNotMatch(architect, /`(?:tools_search|tools_get|tools_run|propose_artifact|request_approval|load_skill|open_canvas|ask_user)`/);
    for (const tool of [
      'ds_read', 'ds_write', 'ds_edit', 'ds_search', 'ds_records', 'ds_workbook',
      'ds_publish', 'ds_plan', 'ds_analytics', 'ds_engage', 'ds_api', 'ds_ask',
    ]) {
      assert.match(architect, new RegExp('`' + tool + '`'));
    }
    assert.match(architect, /ARRAY of paths/);
    assert.match(architect, /skill:\/\/<id>\/<file>\.md/);
    assert.match(architect, /`purpose`/);
    assert.match(architect, /one consolidated popup carrying every remaining question/);
    assert.match(architect, /fix_input, fetch_first, ask_user, or wait/);
    assert.match(architect, /unknown_outcome overrides all of these/);
    assert.match(architect, /Queued is not sent\. Approved is not published\./);
    assert.match(architect, /## Capability routing/);
    const mutates = pinned.skills[id].capability_ids.some((capabilityId: string) => (
      catalog.capabilities.some(
        (capability: { id: string; mutates?: boolean }) => (
          capability.id === capabilityId && capability.mutates === true
        ),
      )
    ));
    if (mutates) {
      assert.match(
        architect,
        /server's ActionDecision determines whether each exact operation auto-runs/,
      );
    }
    for (const client of ['claude', 'codex']) {
      const clientRoot = `generated/client-adapters/${client}/${id}`;
      const standalone = artifacts[`${clientRoot}/SKILL.md`];
      assert.equal(artifacts[`${clientRoot}/KERNEL.md`], artifacts[`${architectRoot}/KERNEL.md`]);
      assert.equal(artifacts[`${clientRoot}/evals.json`], artifacts[`${architectRoot}/evals.json`]);
      for (const [field, expected] of Object.entries(pinned.compatibility)) {
        assert.match(standalone, new RegExp(`^  ${field}: ${String(expected)}$`, 'm'));
      }
      assert.match(standalone, new RegExp(`^  source_release_hash: ${pinned.source_release_hash}$`, 'm'));
      assert.match(standalone, new RegExp(`^  kernel_sha256: ${pinned.skills[id].kernel_sha256}$`, 'm'));
      assert.match(standalone, new RegExp(`^  evals_sha256: ${pinned.skills[id].evals_sha256}$`, 'm'));
      assert.match(standalone, new RegExp(`^  adapter_sha256: ${clients.skills[id].adapter_sha256[client]}$`, 'm'));
      assert.match(standalone, /mismatch_behavior: deny_run/);
      assert.match(standalone, /manifest_digest_match: exact_sha256/);
      assert.match(standalone, /Carry the server's ActionDecision mechanically/);
      assert.match(
        standalone,
        /recovery_operations: \[dreamstate_tools_search, dreamstate_tools_get, dreamstate_proposals_get, dreamstate_get_run, dreamstate_list_runs\]/,
      );
      assert.match(
        standalone,
        /denied_operations: \[dreamstate_tools_run, dreamstate_context_create_document, dreamstate_context_create_folder, dreamstate_context_save_and_publish, dreamstate_context_save_draft, dreamstate_proposals_create, dreamstate_proposals_mutate\]/,
      );
      assert.match(standalone, /Refuse `dreamstate_tools_run` until the installed package is refreshed/);
      assert.match(standalone, /full 64-character SHA-256 manifest digest/i);
      assert.match(standalone, /`dreamstate_tools_search` and `dreamstate_tools_get`/);
      assert.match(standalone, /`dreamstate_proposals_create`/);
      assert.match(standalone, /human review/);
      assert.match(standalone, /`dreamstate_proposals_mutate`/);
      assert.match(standalone, /expected revision and state version/i);
      assert.match(standalone, /revise, approve, or reject/i);
      assert.match(standalone, /When ActionDecision requires a proposal/);
      assert.match(standalone, /returned `run_id`/);
      assert.match(standalone, /`dreamstate_get_run`/);
      assert.match(standalone, /^completion_contract: \{"version":1,"fields":\[/m);
    }
    assert.equal(pinned.skills[id].kernel_sha256, clients.skills[id].kernel_sha256);
    assert.equal(pinned.skills[id].evals_sha256, clients.skills[id].evals_sha256);
    assert.match(
      artifacts[`${architectRoot}/SKILL.md`],
      /bounded structured partial outputs plus the exact next transition/,
    );
    assert.match(artifacts[`${architectRoot}/SKILL.md`], /^completion_contract: \{"version":1,"fields":\[/m);
  }
});

test('action authority is server-owned and no source or generated package carries an action allowlist', () => {
  const artifacts = build();
  const forbidden = /direct_run_capability_ids|direct[- ]run (?:capability )?(?:ids?|allowlist)|complete allowlist for direct mutating|not named in that exact allowlist/i;
  for (const [path, content] of Object.entries(artifacts)) {
    assert.doesNotMatch(content, forbidden, `${path} carries obsolete action authority`);
  }
  for (const skill of architectSource.skills as Array<{ id: string }>) {
    const kernel = readFileSync(join(ROOT, 'architect-kernels', skill.id, 'KERNEL.md'), 'utf8');
    assert.doesNotMatch(kernel, forbidden, `${skill.id}/KERNEL.md carries obsolete action authority`);
  }
});

test('Context is one files-first Markdown graph with a direct-write, approval-bound-lifecycle authority split', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const context = architectSource.skills.find((skill: { id: string }) => skill.id === 'context');
  assert.ok(context);

  // The authority model changed deliberately, it did not erode. `propose_artifact`
  // and `request_approval` were retired with the model-driven proposal flow
  // (decision E1), and the backend now admits authoring as a DIRECT write for an
  // Architect principal: `requireDirectContextEditor`
  // (apps/backend/src/services/brain/brainCapabilityExecutor.ts:316-356) lets
  // create_document, create_folder, save_draft and save_and_publish through with
  // no approval binding, while every lifecycle mutation below still requires one.
  // That split is the real invariant, so this test asserts both halves: authoring
  // is granted, and human review decisions (publish/reject/resolve_conflict) are
  // still not the agent's to make.
  const agentCapabilities = [
    'brain.context.archive_document',
    'brain.context.backlinks',
    'brain.context.browse',
    'brain.context.create_document',
    'brain.context.create_folder',
    'brain.context.delete_document',
    'brain.context.get',
    'brain.context.graph',
    'brain.context.history',
    'brain.context.list_proposals',
    'brain.context.move_document',
    'brain.context.preview_agent_view',
    'brain.context.propose',
    'brain.context.propose_document',
    'brain.context.rebuild_links',
    'brain.context.register_source',
    'brain.context.list',
    'brain.context.rename_document',
    'brain.context.restore_document',
    'brain.context.save_and_publish',
    'brain.context.save_draft',
    'brain.context.search',
    'brain.context.website_source_register',
    'brain.evidence.search',
    'brain.graph.neighborhood',
    'brain.knowledge.digest',
    'brain.knowledge.doc_map',
    'brain.knowledge.document',
    'brain.knowledge.index',
  ].sort();
  assert.deepEqual(pinned.skills.context.capability_ids, agentCapabilities);

  // A package is no longer KERNEL.md plus evals.json. The depth that used to be
  // crammed into one kernel now lives in level-3 supporting files
  // (`skill://context/writing.md` and friends), so the package's prose is the
  // union of them. Reading only KERNEL.md would let a real invariant move one
  // file over and silently stop being asserted.
  const contextDir = join(ROOT, 'architect-kernels', 'context');
  const contextSource = [
    JSON.stringify(context),
    ...readdirSync(contextDir)
      .filter((file) => file.endsWith('.md'))
      .sort()
      .map((file) => readFileSync(join(contextDir, file), 'utf8')),
    readFileSync(join(contextDir, 'evals.json'), 'utf8'),
  ].join('\n');
  assert.match(
    contextSource,
    /Read and write the one files-first workspace wiki/,
  );
  assert.match(contextSource, /a fresh workspace is empty of documents/i);
  assert.match(
    contextSource,
    /The protected workspace roots are exactly `Sources`, `Outreach`, `Social`, `Website`, `Records`/,
  );
  assert.match(contextSource, /Beyond those five seeded, protected system roots, the tree is free-form/);
  assert.match(contextSource, /Source: <url> fetched <date>/);
  assert.match(contextSource, /Provenance lives in the Markdown itself; there is no separate citation ledger and no hidden context/);
  assert.match(contextSource, /author and publish it directly/i);
  assert.match(contextSource, /backlinks.*read-only inspection/i);
  assert.match(contextSource, /governed mutations for a directly authenticated Context editor/i);
  assert.match(contextSource, /delete_document.*irreversible.*fresh owner-exact approval/i);
  assert.doesNotMatch(
    contextSource,
    /Company Brain|Company Context|Personal Context/i,
  );

  // Deciding a human's review is still not the agent's to do. These stay out.
  const excludedGovernanceCapabilities = [
    'brain.context.publish',
    'brain.context.reject',
    'brain.context.resolve_conflict',
  ];
  for (const capabilityId of excludedGovernanceCapabilities) {
    assert.equal(pinned.skills.context.capability_ids.includes(capabilityId), false);
  }
});

test('Architect kernels and evals ground work in the canonical workspace wiki, not retired Brain trees', () => {
  const source = [
    readFileSync(join(ROOT, 'architect-kernels', 'skills.json'), 'utf8'),
    ...(architectSource.skills as Array<{ id: string }>).flatMap((skill) => [
      readFileSync(join(ROOT, 'architect-kernels', skill.id, 'KERNEL.md'), 'utf8'),
      readFileSync(join(ROOT, 'architect-kernels', skill.id, 'evals.json'), 'utf8'),
    ]),
  ].join('\n');
  assert.doesNotMatch(source, /Company Brain|Company Context|Personal Context/i);
});

test('social analytics refresh authority is earned by a real-user eval', () => {
  const artifacts = build();
  const social = JSON.parse(artifacts['generated/architect/social/evals.json']);
  const refreshCase = social.cases.find(
    (item: { id: string }) => item.id === 'refresh-and-diagnose-social-performance',
  );
  assert.ok(refreshCase);
  assert.ok(refreshCase.required_capability_ids.includes('social.analytics_refresh'));
  assert.match(
    artifacts['generated/architect/social/KERNEL.md'],
    /"social\.analytics_refresh"/,
  );
});

test('Architect generation rejects signed capability IDs absent from the pinned registry', () => {
  const withoutRequiredCapability = {
    ...catalog,
    capabilities: catalog.capabilities.filter((capability: { id: string }) => capability.id !== 'sources.cold_outbound_expand'),
  };
  assert.throws(
    () => buildArchitectArtifacts(withoutRequiredCapability),
    /outreach.*capability id sources\.cold_outbound_expand.*pinned capability manifest/i,
  );
});

test('Architect exact grants are derived only from machine-readable eval operation contracts', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const expected = Object.fromEntries(
    architectSource.skills.map((skill: { id: string }) => {
      const evals = JSON.parse(readFileSync(
        join(ROOT, 'architect-kernels', skill.id, 'evals.json'),
        'utf8',
      ));
      const capabilityIds = [...new Set(evals.cases.flatMap(
        (item: { required_capability_ids?: string[] }) => item.required_capability_ids ?? [],
      ))].sort();
      return [skill.id, capabilityIds];
    }),
  );

  for (const [skillId, capabilityIds] of Object.entries(expected)) {
    assert.deepEqual(pinned.skills[skillId].capability_ids, capabilityIds);
    assert.match(
      artifacts[`generated/architect/${skillId}/SKILL.md`],
      new RegExp(`^capability_ids: ${JSON.stringify(capabilityIds).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}$`, 'm'),
    );
  }
  assert.ok(
    architectSource.skills.every((skill: Record<string, unknown>) => !('capability_ids' in skill)),
    'source manifests must not carry a second hand-maintained grant list',
  );
  assert.ok(
    !pinned.skills.context.capability_ids.includes('brain.context.reject'),
    'a canonical id absent from eval operation contracts must never become authority',
  );
});

test('weekly growth coordination earns calendar and task creation authority from a real-user eval', () => {
  const artifacts = build();
  const weekly = JSON.parse(artifacts['generated/architect/planning/evals.json']);
  const coordination = weekly.cases.find(
    (item: { id?: string }) => item.id === 'customer-follow-up-coordination',
  );
  assert.deepEqual(coordination.required_capability_ids, [
    'calendar.events_create',
    'calendar.events_list',
    'tasks.create',
    'tasks.get',
    'record_files.upload',
    'record_files.list',
    'records.get',
  ]);
});

test('site onboarding registers evidence and proposes useful Markdown without imposing a document template', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const capabilityIds = pinned.skills.workspace.capability_ids;
  // site-onboarding was folded into workspace as a supporting file, not a
  // standalone kernel: the short map lives in KERNEL.md and the onboarding
  // depth lives in site-onboarding.md, so the invariant is checked against
  // the combined text a model actually reads for this job.
  const kernel = `${artifacts['generated/architect/workspace/KERNEL.md']}\n${artifacts['generated/architect/workspace/site-onboarding.md']}`;
  const evals = JSON.parse(artifacts['generated/architect/workspace/evals.json']);

  assert.ok(capabilityIds.includes('brain.context.website_source_register'));
  assert.ok(capabilityIds.includes('brain.context.propose_document'));
  assert.equal(capabilityIds.includes('brain.context.create_document'), false);
  assert.equal(capabilityIds.includes('brain.context.save_and_publish'), false);
  assert.match(
    kernel,
    /register the exact website source.*before proposing wiki content/is,
  );
  assert.match(kernel, /Choose file names and organization from the evidence and the request/);
  assert.doesNotMatch(
    kernel,
    /Product Information|Ideal Customer|Competitor Analysis|Tone of Voice|Marketing Strategy/i,
  );
  const freshSite = evals.cases.find((item: { id: string }) => item.id === 'fresh-site-to-proposed-workspace-wiki');
  assert.ok(freshSite);
  assert.match(freshSite.request, /onboard https:\/\/example\.com/i);
  assert.match(freshSite.request, /workspace knowledge our team needs/i);
  assert.ok(freshSite.required_capability_ids.includes('brain.context.website_source_register'));
  assert.ok(freshSite.required_capability_ids.includes('brain.context.propose_document'));
  assert.ok(freshSite.expected_workspace_outcome.some(
    (outcome: { check: string; expected: string }) => (
      outcome.check === 'context_document_revision_attested' && outcome.expected === 'present'
    ),
  ));
});

test('every kernel compliance contract exactly covers its eval-declared operation authority', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  assert.equal(Object.keys(pinned.skills).length, 13);

  // strategy was folded into planning; planning's KERNEL.md operation
  // contract still declares brain.learning.query_benchmarks and the same
  // drift-detection invariant applies to its new owner.
  const path = join(ROOT, 'architect-kernels', 'planning', 'KERNEL.md');
  const original = readFileSync(path, 'utf8');
  const drifted = original.replace(
    '"brain.learning.query_benchmarks",',
    '',
  );
  assert.notEqual(drifted, original);
  try {
    writeFileSync(path, drifted);
    assert.throws(
      () => buildArchitectArtifacts(catalog),
      /planning.*operation contract.*eval-declared capability authority/i,
    );
  } finally {
    writeFileSync(path, original);
  }
});

test('Architect generation requires a full canonical manifest digest', () => {
  assert.throws(
    () => buildArchitectArtifacts({ ...catalog, manifest_digest: CANONICAL_MANIFEST_DIGEST.slice(0, 16) }),
    /manifest digest is invalid/i,
  );
});

test('signed capability domains stay identical across source, Architect, Claude, Codex, and release manifests', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const clients = JSON.parse(artifacts['generated/client-adapters/RELEASE.json']);
  const expected: Record<string, string[]> = {
    analytics: [
      'analytics', 'attribution', 'command_center', 'gtm', 'outreach',
      'page_analytics', 'sequences', 'social', 'visibility', 'workflows',
    ],
    context: ['brain'],
    crm: [
      'brain', 'products', 'record_attributes', 'record_deals', 'record_definitions',
      'record_exports', 'record_files', 'record_imports', 'record_objects',
      'record_pipeline_stages', 'record_pipelines', 'record_relationships',
      'record_templates', 'records', 'saved_views', 'tasks',
    ],
    outreach: [
      'attachments', 'audiences', 'brain', 'cells', 'columns', 'executable_definitions',
      'executables', 'graph', 'outreach', 'radar', 'record_enrichment', 'records', 'rows',
      'runs', 'selection_snapshots', 'sequences', 'signal_sources', 'sources', 'table_runs',
      'table_sources', 'tables', 'views', 'workbook_audiences', 'workbooks', 'workflows',
      'worksheets',
    ],
    planning: [
      'brain', 'calendar', 'command_center', 'content', 'growth', 'gtm', 'identity',
      'outreach', 'record_files', 'records', 'sequences', 'social', 'tasks', 'visibility',
      'workbooks', 'workflows',
    ],
    'seo-geo': ['brain', 'integrations', 'seo', 'tools', 'visibility'],
    sequences: ['brain', 'outreach', 'rows', 'sequences'],
    social: ['brain', 'content', 'social', 'tools'],
    'social.linkedin': ['brain', 'social', 'tables'],
    'social.reddit': ['brain', 'social', 'tables'],
    'social.x': ['brain', 'social', 'tables'],
    workspace: [
      'brain', 'integrations', 'mailboxes', 'notifications', 'outreach', 'products',
      'seo', 'visibility', 'webhooks', 'workspace',
    ],
    writing: ['brain', 'content', 'research'],
  };

  assert.deepEqual(
    Object.fromEntries(architectSource.skills.map((skill: { id: string; capability_domains: string[] }) => [
      skill.id,
      skill.capability_domains,
    ])),
    expected,
  );
  for (const [id, capabilityDomains] of Object.entries(expected)) {
    assert.deepEqual(pinned.skills[id].capability_domains, capabilityDomains);
    assert.deepEqual(clients.skills[id].capability_domains, capabilityDomains);
    for (const root of [
      `generated/architect/${id}`,
      `generated/client-adapters/claude/${id}`,
      `generated/client-adapters/codex/${id}`,
    ]) {
      assert.ok(
        artifacts[`${root}/SKILL.md`].split('\n').includes(
          `capability_domains: ${JSON.stringify(capabilityDomains)}`,
        ),
        `${root}/SKILL.md must carry the signed capability domain closure`,
      );
    }
  }
  // outreach-workflow-builder was folded into outreach; the same
  // eval-derived-exact-grant invariant is checked against its new owner.
  const outreachEvals = JSON.parse(
    artifacts['generated/architect/outreach/evals.json'],
  );
  const exactCapabilityIds = [...new Set(outreachEvals.cases.flatMap(
    (item: { required_capability_ids?: string[] }) => item.required_capability_ids ?? [],
  ))].sort();
  assert.equal(
    'capability_ids' in architectSource.skills.find(
      (skill: { id: string }) => skill.id === 'outreach',
    ),
    false,
  );
  assert.deepEqual(pinned.skills.outreach.capability_ids, exactCapabilityIds);
  assert.deepEqual(clients.skills.outreach.capability_ids, exactCapabilityIds);
  for (const root of [
    'generated/architect/outreach',
    'generated/client-adapters/claude/outreach',
    'generated/client-adapters/codex/outreach',
  ]) {
    assert.ok(
      artifacts[`${root}/SKILL.md`].split('\n').includes(`capability_ids: ${JSON.stringify(exactCapabilityIds)}`),
      `${root}/SKILL.md must carry the signed exact capability closure`,
    );
  }
});

test('audience planning kernels require privacy-safe pooled benchmark evidence', () => {
  const artifacts = build();
  const outreach = JSON.parse(artifacts['generated/architect/outreach/evals.json']);
  // outreach-workflow-builder's zero-history-restaurant-owners case was
  // consolidated into outreach's own fixed-cohort case, which carries the
  // same fixed-quantity, never-targeted-before, privacy-safe-benchmark shape.
  const restaurantOwners = outreach.cases.find((item: { id: string }) => item.id === 'fixed-cohort-and-zero-history-benchmark');
  assert.ok(restaurantOwners);
  for (const concept of ['insufficient_evidence', 'never raw cross-workspace rows', 'cohort-level evidence only']) {
    assert.ok(restaurantOwners.required_concepts.includes(concept));
  }
  assert.deepEqual(restaurantOwners.required_capability_ids, ['outreach.demand_plan_get', 'brain.learning.query_benchmarks']);
  assert.match(restaurantOwners.request, /restaurant owners/i);
  assert.match(restaurantOwners.request, /never targeted this cohort before/i);
  assert.doesNotMatch(restaurantOwners.request, /brain\.learning\.query_benchmarks|privacy boundary|sample band/i);

  const social = JSON.parse(artifacts['generated/architect/social/evals.json']);
  assert.ok(social.cases.some((item: { id: string }) => item.id === 'founder-posts-pooled-benchmark'));
  const seo = JSON.parse(artifacts['generated/architect/seo-geo/evals.json']);
  assert.ok(seo.cases.some((item: { id: string }) => item.id === 'keyword-plan-with-benchmark'));
  const technicalSeo = seo.cases.find((item: { id: string }) => item.id === 'technical-and-content-audit');
  assert.ok(technicalSeo);
  for (const pattern of [/owninfluence\.com/, /US-English marketing agencies/, /demo bookings/, /buffer\.com/, /hootsuite\.com/, /prioritized plan/, /technical and content gaps/]) {
    assert.match(technicalSeo.request, pattern);
  }
  assert.doesNotMatch(technicalSeo.request, /fast-triage|read-only|seo\.robots_audit/i);
  const seoKernel = artifacts['generated/architect/seo-geo/KERNEL.md'];
  assert.match(seoKernel, /State `insufficient_evidence` when the result is sparse, suppressed, or irrelevant/);
  assert.match(
    artifacts['generated/architect/outreach/workflow-and-handoff.md'],
    /Sparse or suppressed evidence is reported as `insufficient_evidence`, not treated as a reason to stop the job/i,
  );
  assert.match(seoKernel, /call `brain\.learning\.query_benchmarks`/);
  assert.match(seoKernel, /never expose raw cross-workspace rows/);
});

// This invariant now lives specifically in the per-platform social.x package
// (the other platform kernels do not carry it): the exact wording moved with
// consolidation but the "do not block a scoped read on optional presentation
// choices" rule still holds.
test('social research executes scoped reads without blocking on optional presentation choices', () => {
  const kernel = build()['generated/architect/social.x/KERNEL.md'];
  assert.match(kernel, /topic or query and time window/i);
  assert.match(kernel, /ranking and output (?:format )?choices are optional/i);
  assert.match(kernel, /transparent defaults/i);
  assert.match(kernel, /nullable metrics/i);
  assert.match(kernel, /Ask only for truly required missing inputs/i);
});

test('a standalone Claude or Codex package keeps discovery usable but denies mutation on compatibility drift', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/client-adapters/RELEASE.json']);
  const mutationOperations = new Set([
    'dreamstate_tools_run',
    'dreamstate_context_create_document',
    'dreamstate_context_create_folder',
    'dreamstate_context_save_and_publish',
    'dreamstate_context_save_draft',
    'dreamstate_proposals_create',
    'dreamstate_proposals_mutate',
  ]);
  for (const client of ['claude', 'codex']) {
    const standalone = artifacts[`generated/client-adapters/${client}/context/SKILL.md`];
    const scalar = (field: string) => standalone.match(new RegExp(`^  ${field}: (.+)$`, 'm'))?.[1];
    const installed = {
      capability_definition_version: scalar('capability_definition_version'),
      capability_hash: scalar('capability_hash'),
      manifest_digest: scalar('manifest_digest'),
      minimum_api_version: scalar('minimum_api_version'),
    };
    assert.deepEqual(installed, {
      capability_definition_version: pinned.compatibility.capability_definition_version,
      capability_hash: pinned.compatibility.capability_hash,
      manifest_digest: pinned.compatibility.manifest_digest,
      minimum_api_version: pinned.compatibility.minimum_api_version,
    });
    // Dedicated Context write tools are mutation paths too. Compatibility
    // drift must deny them alongside the canonical run and proposal paths.
    const deniedOperations = standalone
      .match(/^  denied_operations: \[([^\]]+)\]$/m)?.[1]
      .split(', ')
      .sort();
    assert.deepEqual(deniedOperations, [...mutationOperations].sort());
    assert.equal(installed.manifest_digest, CANONICAL_MANIFEST_DIGEST);
    const live = { ...installed, manifest_digest: 'f'.repeat(64) };
    const compatible = Object.entries(installed).every(([key, value]) => live[key as keyof typeof live] === value);
    const permits = (operation: string) => !mutationOperations.has(operation) || compatible;
    for (const operation of [
      'dreamstate_tools_search',
      'dreamstate_tools_get',
      'dreamstate_proposals_get',
      'dreamstate_get_run',
      'dreamstate_list_runs',
    ]) assert.equal(permits(operation), true, `${client} must retain ${operation} for recovery`);
    for (const operation of mutationOperations) {
      assert.equal(permits(operation), false, `${client} must deny ${operation} on digest drift`);
    }
  }
});

// The gateway now carries two families: the retired-but-still-served
// `dreamstate_*` recovery/discovery/proposal tools kept for standalone
// Claude/Codex adapters (see the compatibility-drift test above), plus the
// twelve live `ds_*` tools Architect itself calls. Neither family exposes a
// raw `register_source`-style escape hatch.
test('the pinned MCP catalog exposes only the compact governed gateway', () => {
  assert.deepEqual(catalog.mcp_tools.map((tool: { name: string }) => tool.name).sort(), [
    'dreamstate_agent_proposal_create',
    'dreamstate_agent_proposal_delegate_bindings',
    'dreamstate_agent_proposal_get',
    'dreamstate_cancel_run',
    'dreamstate_get_run',
    'dreamstate_list_runs',
    'dreamstate_resume_run',
    'dreamstate_tools_get',
    'dreamstate_tools_run',
    'dreamstate_tools_search',
    'ds_analytics',
    'ds_api',
    'ds_ask',
    'ds_edit',
    'ds_engage',
    'ds_plan',
    'ds_publish',
    'ds_read',
    'ds_records',
    'ds_search',
    'ds_workbook',
    'ds_write',
    'ping',
  ]);
  assert.equal(
    catalog.mcp_tools.some((tool: { name: string }) => /register_source/.test(tool.name)),
    false,
  );
});

test('generated Architect outreach packages contain no shortcut terminology', () => {
  const artifacts = build();
  const forbidden = /\b(?:templates?|presets?|reusable|reuse)\b/i;
  // outreach-workflow-builder merged into outreach; outreach-sequence-writer
  // merged into sequences. Every generated file for both packages, including
  // the supporting files that now carry the depth SKILL.md used to inline,
  // must stay clean.
  for (const id of ['outreach', 'sequences']) {
    for (const [path, content] of Object.entries(artifacts)) {
      if (path.startsWith(`generated/architect/${id}/`) && path.endsWith('.md')) {
        assert.doesNotMatch(content, forbidden, path);
      }
      if (path === `generated/architect/${id}/evals.json`) {
        assert.doesNotMatch(content, forbidden, path);
      }
    }
  }

  const index = JSON.parse(artifacts['skills-index.json']);
  const outreachSkills = index.skills.filter((skill: { domain: string }) => skill.domain === 'outreach');
  for (const skill of outreachSkills) {
    assert.equal(skill.mcp_tools.includes('outreach_apply_template'), false, `${skill.slug}: forbidden agent shortcut tool`);
    assert.equal(skill.capability_ids.includes('intent:outreach.apply_template'), false, `${skill.slug}: forbidden agent shortcut capability`);
    assert.equal(skill.run_intents.includes('outreach.apply_template'), false, `${skill.slug}: forbidden agent shortcut intent`);
  }
  assert.doesNotMatch(artifacts['generated/site/skills-catalog.json'], /outreach_apply_template|intent:outreach\.apply_template|outreach\.apply_template/);
});

test('active Architect outreach sources are campaign-free and reject retired campaign contracts', () => {
  const artifacts = build();
  const retiredEvalLanguage = /campaigns\.|campaign_state|campaign_id|outreach_campaigns|campaignId|outreachCampaignId|\bLaunch Campaign\b|\bcampaign(?:s|[-_][a-z0-9_]+)?\b/i;
  // tables, outreach-workflow-builder, and outreach-sequence-writer merged
  // into outreach and sequences; those two are the only packages the build
  // now tracks in ACTIVE_OUTREACH_KERNEL_IDS (scripts/architect-build.ts).
  for (const id of ['outreach', 'sequences']) {
    assert.doesNotMatch(
      artifacts[`generated/architect/${id}/KERNEL.md`],
      retiredEvalLanguage,
      `${id}: active model-visible kernel language must use workbook, workflow, and sequence identities`,
    );
  }

  for (const id of ['outreach', 'sequences']) {
    const evals = JSON.parse(artifacts[`generated/architect/${id}/evals.json`]);
    assert.doesNotMatch(JSON.stringify(evals), retiredEvalLanguage, `${id}: retired eval identity or authority`);
  }
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  for (const id of Object.keys(pinned.skills)) {
    assert.equal(
      pinned.skills[id].capability_ids.some((capabilityId: string) => capabilityId.startsWith('campaigns.')),
      false,
      `${id}: retired campaign grant`,
    );
  }

  const path = join(ROOT, 'architect-kernels', 'sequences', 'KERNEL.md');
  const original = readFileSync(path, 'utf8');
  for (const retiredIdentity of ['campaign_id', 'outreach_campaigns', 'campaignId', 'outreachCampaignId']) {
    try {
      writeFileSync(path, `${original}\nRetired identity: ${retiredIdentity}.\n`);
      assert.throws(
        () => buildArchitectArtifacts(catalog),
        /sequences.*retired campaign.*(?:identity|terminology)/i,
      );
    } finally {
      writeFileSync(path, original);
    }
  }

  const evalPath = join(ROOT, 'architect-kernels', 'outreach', 'evals.json');
  const originalEvals = readFileSync(evalPath, 'utf8');
  const driftedEvals = JSON.parse(originalEvals);
  driftedEvals.cases[0].request = 'Bind campaign_id and propose Launch Campaign.';
  try {
    writeFileSync(evalPath, `${JSON.stringify(driftedEvals, null, 2)}\n`);
    assert.throws(
      () => buildArchitectArtifacts(catalog),
      /outreach.*retired campaign.*(?:identity|terminology|capability|state)/i,
    );
  } finally {
    writeFileSync(evalPath, originalEvals);
  }

  const manifestPath = join(ROOT, 'architect-kernels', 'skills.json');
  const originalManifest = readFileSync(manifestPath, 'utf8');
  const driftedManifest = JSON.parse(originalManifest);
  driftedManifest.skills.find((skill: { id: string }) => skill.id === 'outreach')
    .triggers.push('Launch Campaign');
  try {
    writeFileSync(manifestPath, `${JSON.stringify(driftedManifest, null, 2)}\n`);
    assert.throws(
      () => buildArchitectArtifacts(catalog),
      /outreach.*retired campaign.*(?:artifact|identity|terminology)/i,
    );
  } finally {
    writeFileSync(manifestPath, originalManifest);
  }
});

// outreach-workflow-builder merged into outreach itself, so workflow
// authoring (workflows.create/graph_apply) is no longer split across a
// separate specialist: outreach now owns that authoring directly. The part
// of the original invariant that still has two distinct packages to check is
// message authoring: `sequences` (message copy, timing, sender binding)
// stays separate from `outreach` (which owns only launch closure over an
// already-authored, already-validated sequence).
test('outreach owns workflow authoring directly, but message authoring stays specialist-owned in sequences while outreach keeps only launch closure', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  for (const capabilityId of ['workflows.create', 'workflows.graph_apply']) {
    assert.ok(pinned.skills.outreach.capability_ids.includes(capabilityId), `outreach: ${capabilityId}`);
  }
  assert.ok(pinned.skills.sequences.capability_ids.includes('sequences.bind'), 'sequences: sequences.bind');
  assert.equal(pinned.skills.outreach.capability_ids.includes('sequences.bind'), false, 'coordinator must not own sequences.bind');
  for (const capabilityId of [
    'workflows.draft_publish',
    'workflows.activate',
    'sequences.publish',
    'sequences.enroll_selection',
  ]) {
    assert.ok(pinned.skills.outreach.capability_ids.includes(capabilityId), `coordinator launch closure: ${capabilityId}`);
    assert.equal(pinned.skills.sequences.capability_ids.includes(capabilityId), false, `sequences must not own launch closure: ${capabilityId}`);
  }
});

// tables, outreach-workflow-builder, and outreach-sequence-writer all merged
// into outreach, so the cross-package "tables hands a typed reviewed result
// to the workflow specialist" text no longer exists (there is nothing left to
// hand off across a package boundary). What survives is the deeper
// invariant: outreach owns workbook creation and canonical source
// preview/expansion, and no other of the 13 live packages declares those
// capability ids.
test('outreach is the only package owner of workbook creation and canonical source preview and expansion', () => {
  const artifacts = build();
  const pinned = JSON.parse(artifacts['generated/architect/PINNED_RELEASE.json']);
  const allSkillIds = Object.keys(pinned.skills);
  for (const capabilityId of [
    'workbooks.create',
    'table_sources.preview',
    'sources.cold_outbound_expand',
    'sources.cold_outbound_preview',
    'sources.linkedin_post_engagers_preview',
  ]) {
    const owners = allSkillIds.filter((skillId) => pinned.skills[skillId].capability_ids.includes(capabilityId));
    assert.deepEqual(owners, ['outreach'], `${capabilityId}: exactly one package owner`);
  }
});

// `new-workflow-from-scratch` and `competitor-engagers-canonical-full-journey`
// were consolidated into `icp-discovery-one-popup`, `workbook-first-before-any-bundle`,
// and `competitor-engagers-qualify-and-price`. The old `required_tool_sequence`
// phase-name mechanism is gone (evals.json no longer carries that field
// anywhere, see the eight-tool-harness test above); order is now expressed
// through `required_executed_capability_ids`, an ordered array of real
// capability ids, plus `required_concepts` prose.
test('outreach is wiki-first and Workbook-first before demand, workflow, or sequence planning', () => {
  const artifacts = build();
  const kernel = artifacts['generated/architect/outreach/KERNEL.md'];
  const icp = artifacts['generated/architect/outreach/icp.md'];
  const evals = JSON.parse(artifacts['generated/architect/outreach/evals.json']);

  const scratch = evals.cases.find((item: { id: string }) => item.id === 'icp-discovery-one-popup');
  assert.ok(scratch);
  assert.deepEqual(scratch.must_use_popup_when_missing, ['qualification']);
  assert.ok(scratch.forbidden_question_concepts.includes('sender'));
  assert.ok(scratch.forbidden_question_concepts.includes('channel'));
  assert.match(
    icp,
    /Derive as many as you can from `brain\.context\.search` \/ `brain\.context\.get` \(published workspace claims\).*ask only for what remains missing/is,
  );
  assert.match(kernel, /sender.*channel.*launch/is);
  const messagingCase = evals.cases.find((item: { id: string }) => item.id === 'sequence-only-when-messaging');
  assert.ok(messagingCase.required_concepts.includes('messaging branch state is inspection-only'));

  const workbookFirst = evals.cases.find((item: { id: string }) => item.id === 'workbook-first-before-any-bundle');
  assert.ok(workbookFirst);
  assert.ok(workbookFirst.expected_workspace_outcome.some((outcome: { check: string; expected: string; reason: string }) => (
    outcome.check === 'workbook_enrolled'
    && outcome.expected === 'absent'
    && /no demand, workflow, sequence, or bundle work happens before the Workbook revision is inspected/.test(outcome.reason)
  )));

  const qualifyAndPrice = evals.cases.find((item: { id: string }) => item.id === 'competitor-engagers-qualify-and-price');
  assert.ok(qualifyAndPrice);
  const executed = qualifyAndPrice.required_executed_capability_ids as string[];
  const workbookIndex = executed.indexOf('workbooks.create');
  const demandIndex = executed.indexOf('outreach.demand_plan_get');
  assert.ok(workbookIndex >= 0 && demandIndex > workbookIndex, 'Workbook must be created before any demand plan is fetched');
  assert.ok(qualifyAndPrice.required_concepts.includes('Workbook created before any demand plan is fetched'));
});

test('outreach launch closure and pilot invariants use the canonical workflow and sequence surface', () => {
  const artifacts = build();
  const kernel = artifacts['generated/architect/outreach/KERNEL.md'];
  const sources = artifacts['generated/architect/outreach/sources.md'];
  const evals = JSON.parse(artifacts['generated/architect/outreach/evals.json']);
  assert.match(sources, /`row_limit: 10`/);
  assert.match(sources, /exactly ten distinct stable identities/i);
  assert.match(sources, /Never pad short results with duplicate or synthetic rows to hit ten/i);
  // "no import, no enrollment" is now stated as "no durable destination and
  // never lands a row": a preview cannot produce either effect.
  assert.match(sources, /A preview has no durable destination and never lands a row/i);

  // explicit-final-launch-revalidation was consolidated into
  // competitor-engagers-enroll-and-launch. The `sequence_publish_required`
  // and `mutating_capability_budget` fields it used to carry are gone from
  // the schema entirely (not just this case), so only the surviving
  // launch-closure-capability-presence invariant is checked.
  const launch = evals.cases.find((item: { id: string }) => item.id === 'competitor-engagers-enroll-and-launch');
  assert.ok(launch);
  for (const capabilityId of [
    'workflows.draft_publish',
    'workflows.activate',
    'sequences.enroll_selection',
    'sequences.publish',
  ]) {
    assert.ok(launch.required_capability_ids.includes(capabilityId), `${capabilityId}: launch closure`);
  }

  const coordinatorGrant = JSON.parse(
    artifacts['generated/architect/PINNED_RELEASE.json'],
  ).skills.outreach.capability_ids;
  assert.equal(coordinatorGrant.includes('sequences.bind'), false, 'sequences.bind: specialist-owned by sequences');
});

// growth-asset-planner merged into planning as the assets.md supporting file.
test('growth asset planning may describe a buyer template library but stays explicitly unsaved without a capability', () => {
  const artifacts = build();
  const assets = artifacts['generated/architect/planning/assets.md'];
  assert.match(assets, /template library/i);
  const evals = JSON.parse(artifacts['generated/architect/planning/evals.json']);
  const assetCase = evals.cases.find((item: { id: string }) => item.id === 'asset-unsaved-proposal');
  assert.ok(assetCase);
  assert.equal(assetCase.must_state_unsaved_without_capability, true);
  assert.match(assets, /explicitly unsaved proposal/i);
});

// The old model-tracked, named change_kind staging scheme (outreach_source,
// outreach_workbook, outreach_bundle, table_column_run, outreach_bulk_expansion,
// outreach_activation with request_approval per artifact_type) is retired by
// design, not by accident: the new SKILL.md says so explicitly ("The prior
// model-driven proposal flow (propose an artifact, then request approval on
// it) is retired: there is no tool for either step and nothing to build in
// their place"). Authority now comes from the server's own ActionDecision on
// each capability call. What survives from this test's original intent is
// checked directly: pilot-before-commit, one approval never covering another,
// demand-based volume defaults, previews never landing rows, and workflow
// drafts never running or enrolling anything.
test('outreach kernels keep evidence pilot, build, sample, bulk expansion, and launch as separately gated steps', () => {
  const artifacts = build();
  const coordinator = artifacts['generated/architect/outreach/KERNEL.md'];
  const sources = artifacts['generated/architect/outreach/sources.md'];
  const fitScoring = artifacts['generated/architect/outreach/fit-scoring-and-economics.md'];
  const workflow = artifacts['generated/architect/outreach/workflow-and-handoff.md'];
  const evals = JSON.parse(artifacts['generated/architect/outreach/evals.json']);

  assert.match(workflow, /Launch: the single reviewed closure/i);
  assert.match(sources, /source evidence pilot|Test first, at limit 10/i);
  assert.match(coordinator, /outreach\.demand_plan_get/);
  assert.match(sources, /`row_limit: 10`/i);
  assert.match(fitScoring, /default.*demand-based/i);
  assert.match(sources, /no durable destination/i);
  assert.match(sources, /sources\.cold_outbound_expand/);
  assert.match(fitScoring, /smallest representative selection/i);
  assert.match(fitScoring, /Approval of one selection never authorizes another/i);
  assert.match(
    workflow,
    /A draft save or apply never runs a column, enrolls a contact, expands a source, or activates sending/i,
  );

  const launch = evals.cases.find((item: { id: string }) => item.id === 'competitor-engagers-enroll-and-launch');
  assert.ok(launch.required_concepts.includes('single reviewed launch closure'));
  assert.match(workflow, /workflows\.draft_publish/);
});

// Several case ids this test named (staged-pilot-build-sample-expand-launch,
// explicit-final-launch-revalidation, typed-reviewed-tables-handoff) and the
// entire per-case `required_completion_fields` field are gone from the new
// schema (evals.json no longer carries `required_completion_fields`,
// `stage_boundary_state`, `external_send_state`, or `selection_state`
// anywhere; only the skill-level `completion_contract` in SKILL.md remains).
// `outreach-workflow-builder` merged into `outreach`, so there is no second
// evals.json to read a workflow-only case from. What survives is checked
// against the cases and files that actually carry it now.
test('outreach release uses exact capability evidence and signed lifecycle states', () => {
  const artifacts = build();
  const outreach = JSON.parse(artifacts['generated/architect/outreach/evals.json']);
  const conditional = outreach.cases.find((item: { id: string }) => item.id === 'sequence-only-when-messaging');
  const workflowDesign = outreach.cases.find((item: { id: string }) => item.id === 'workflow-graph-design-and-validate');

  assert.equal(conditional.must_use_popup_when_missing, undefined);
  assert.deepEqual(conditional.forbidden_question_concepts, ['messaging_branch_state']);
  assert.equal(conditional.max_intake_checkpoints, undefined);
  assert.ok(conditional.required_concepts.includes('messaging branch state is inspection-only'));

  assert.ok(workflowDesign);
  for (const concept of [
    'hard exclusions before any credit-bearing work',
    'eligibility is separate from enrollment',
    'enrollment is separate from activation',
  ]) {
    assert.ok(workflowDesign.required_concepts.includes(concept));
  }
  assert.ok(workflowDesign.expected_workspace_outcome.some((outcome: { check: string; expected: string }) => (
    outcome.check === 'workflow_activated' && outcome.expected === 'absent'
  )));

  const icpPopup = outreach.cases.find((item: { id: string }) => item.id === 'icp-discovery-one-popup');
  assert.deepEqual(icpPopup.must_use_popup_when_missing, ['qualification']);
  assert.equal(icpPopup.max_intake_checkpoints, 1);
  assert.deepEqual(icpPopup.forbidden_question_concepts, ['outreach_volume', 'sender', 'channel']);
  assert.equal(icpPopup.required_capability_ids.includes('outreach.demand_plan_get'), false);
});

// The single-case, hand-numbered `required_tool_sequence` journey
// (competitor-engagers-canonical-full-journey, phase names like
// `single_launch_approval_qualified_only_activation_enrollment_paced_send`)
// and its four dedicated adversarial-failure cases no longer exist: that
// case was split into `competitor-engagers-qualify-and-price` and
// `competitor-engagers-enroll-and-launch`, and `execution_profile`,
// `expected_load_order`, `forbidden_test_substitutions`, and
// `required_terminal_receipts` are gone from outreach's evals.json entirely
// (verified: none of those four fields appears anywhere in the file). The
// four narrowly-named adversarial cases this test asserted by id
// (competitor-engagers-missing-enrichment-blocks-ai,
// -required-failures-disqualify, -capacity-change-blocks-launch,
// -stale-and-low-precision-audit) have no case-for-case replacement; only
// the capacity one survives as `launch-blocked-capacity-race`. This is a
// real reduction in dedicated adversarial eval coverage for outreach's
// failure paths (missing enrichment, deterministic disqualification, and
// low-precision audit no longer have their own eval case), even though the
// underlying rules are still stated in kernel prose. Reported, not silently
// dropped: see the task report.
test('competitor engager release evals preserve qualify/price, enroll/launch, and capacity-blocked-launch contracts', () => {
  const artifacts = build();
  const outreach = JSON.parse(artifacts['generated/architect/outreach/evals.json']);

  const qualifyAndPrice = outreach.cases.find((item: { id: string }) => item.id === 'competitor-engagers-qualify-and-price');
  assert.deepEqual(qualifyAndPrice.expected_skill_ids, ['outreach']);
  assert.equal(qualifyAndPrice.max_intake_checkpoints, 1);
  assert.deepEqual(qualifyAndPrice.forbidden_question_concepts, [
    'outreach_volume', 'sender', 'channel', 'messaging_branch_state',
  ]);
  assert.match(qualifyAndPrice.request, /people in our ICP/i);
  assert.match(qualifyAndPrice.request, /engage with competitors/i);
  assert.doesNotMatch(qualifyAndPrice.request, /table_sources\.preview|exactly ten real rows|asking approval/i);
  assert.ok(qualifyAndPrice.expected_workspace_outcome.some((outcome: { check: string; expected: string }) => (
    outcome.check === 'workbook_enrolled' && outcome.expected === 'absent'
  )));
  assert.ok(qualifyAndPrice.expected_workspace_outcome.some((outcome: { check: string; expected: string }) => (
    outcome.check === 'workflow_activated' && outcome.expected === 'absent'
  )));

  const enrollAndLaunch = outreach.cases.find((item: { id: string }) => item.id === 'competitor-engagers-enroll-and-launch');
  assert.deepEqual(enrollAndLaunch.forbidden_question_concepts, [
    'outreach_volume', 'sender', 'channel', 'messaging_branch_state',
  ]);
  assert.ok(enrollAndLaunch.required_concepts.includes('fresh demand revalidation immediately before and after the launch proposal'));
  assert.ok(enrollAndLaunch.required_concepts.includes('sequence publication only when inspection shows it is still draft'));

  const capacity = outreach.cases.find((item: { id: string }) => item.id === 'launch-blocked-capacity-race');
  assert.ok(capacity);
  assert.ok(capacity.required_concepts.includes('a capacity drop since the approval blocks launch and must be replanned'));
  assert.ok(capacity.expected_workspace_outcome.some((outcome: { check: string; expected: string }) => (
    outcome.check === 'workflow_activated' && outcome.expected === 'absent'
  )));
  assert.ok(capacity.expected_workspace_outcome.some((outcome: { check: string; expected: string }) => (
    outcome.check === 'workbook_enrolled' && outcome.expected === 'absent'
  )));

  const sources = artifacts['generated/architect/outreach/sources.md'];
  assert.match(sources, /exactly ten distinct stable identities/);
  const columns = artifacts['generated/architect/outreach/columns-and-enrichment.md'];
  assert.match(columns, /not a raw provider dump/);
  const workflow = artifacts['generated/architect/outreach/workflow-and-handoff.md'];
  assert.match(workflow, /freezes an exact reviewed row set, by stable identity/);
  const fitScoring = artifacts['generated/architect/outreach/fit-scoring-and-economics.md'];
  assert.match(fitScoring, /A null value.*is `unsure`, stays visible, and never disqualifies/is);

  assert.match(
    artifacts['generated/architect/sequences/KERNEL.md'],
    /greeting, pitch paragraphs, CTA, sign-off/,
  );
  assert.match(workflow, /follow every accepted job to its terminal receipt/i);
});

// tables merged into outreach. The old schema-building case
// (build-reactive-table, granting bare `tables.create`) and the
// `fixture_profile`/`required_completion_fields` fields it used to assert
// against are gone; the surviving equivalents are `custom-executable-save-and-run`
// (executables.save/run) and `column-sample-run-and-price` (price before you
// run, on a bounded sample).
test('outreach evals require exact executable-save contracts and price-before-run sample discipline', () => {
  const artifacts = build();
  const outreach = JSON.parse(artifacts['generated/architect/outreach/evals.json']);
  const runExecutable = outreach.cases.find(
    (item: { id: string }) => item.id === 'custom-executable-save-and-run',
  );
  const paidSample = outreach.cases.find((item: { id: string }) => item.id === 'column-sample-run-and-price');

  assert.ok(['executables.save', 'executables.run'].every((id) => runExecutable.required_capability_ids.includes(id)));
  assert.ok(runExecutable.required_concepts.includes('library search comes first, custom executable is the fallback'));

  assert.ok(['table_runs.preview_cost', 'columns.run'].every((id) => paidSample.required_capability_ids.includes(id)));
  assert.ok(paidSample.required_concepts.includes('preview_cost before a paid run'));
  assert.ok(paidSample.required_concepts.includes('5 to 10 row sample'));

  assert.match(
    artifacts['generated/architect/outreach/fit-scoring-and-economics.md'],
    /treat its number as the number, not an estimate to round from/i,
  );
});

// tables merged into outreach (which, per the executable-save/price-before-run
// test above, carries no production-local-* case of its own); records,
// records-schema, records-pipelines, records-transfer, records-views, and
// buyer-research-graph merged into crm; experiments merged into planning. The
// workspace_local_approved_mutation eval shape itself survived unchanged.
test('workspace-local production evals require exact approval and durable present outcomes', () => {
  const artifacts = build();
  const productionSkillIds = ['crm', 'planning'];
  const production = productionSkillIds.flatMap((skillId) => (
    JSON.parse(artifacts[`generated/architect/${skillId}/evals.json`]).cases
  ))
    .filter((item: { id: string }) => item.id.startsWith('production-local-'));

  assert.equal(production.length, 6);
  assert.equal(production.filter((item: { skill_id?: string }) => item.skill_id === undefined).length, 6);
  for (const item of production) {
    assert.equal(item.execution_profile, 'production_real');
    assert.equal(item.fixture_profile, 'workspace_local_approved_mutation');
    assert.equal(item.resume_after_approval, 'owner_exact');
    assert.deepEqual(item.allowed_consequence_levels, ['draft_write']);
    assert.ok(item.approved_mutation_capability_ids.length > 0);
    assert.ok(item.approved_mutation_capability_ids.every(
      (capabilityId: string) => item.required_capability_ids.includes(capabilityId),
    ));
    // The old "max_changes >= count of approved mutation capability ids" bound
    // was inferred only from tables' single-domain examples and does not hold
    // generally now that crm exposes it too: production-local-person-record
    // legitimately grants two capability ids (record_objects.record_create,
    // records.create) for what settles as one durable record row. Only the
    // budget's shape (a small positive bound) is checked here.
    assert.ok(item.approved_mutation_max_changes >= 1);
    assert.ok(item.approved_mutation_max_changes <= 8);
    assert.equal(item.required_tool_sequence, undefined);
    assert.ok(item.expected_workspace_outcome.some(
      (outcome: { expected?: string }) => outcome.expected === 'present',
    ));
    assert.equal(item.must_not_request_secrets, true);
    assert.ok(item.forbidden_test_substitutions.length > 0);
  }
});

// The real incident: a description ending "...rows: any durable dataset
// deliverable belongs to tables." was emitted unquoted, YAML read `rows:` as a
// nested mapping, and 28 downstream Python tests died on a file that `npm run
// build`, 63 upstream tests, the release sync, and the consistency checker had
// all just declared healthy. The build must now refuse to emit prose it cannot
// read back.
test('generated frontmatter is validated at emit time: unquotable prose fails the build', () => {
  const fixtureRoot = mkdtempSync(join(tmpdir(), 'dreamstate-frontmatter-'));
  const sourceDir = join(fixtureRoot, 'architect-kernels');
  const manifestPath = join(sourceDir, 'skills.json');
  const victim = 'outreach';
  const authored = architectSource.skills.find(
    (skill: { id: string }) => skill.id === victim,
  ).description;
  const withDescription = (description: string) => {
    const next = structuredClone(architectSource);
    next.skills.find((skill: { id: string }) => skill.id === victim).description = description;
    writeFileSync(manifestPath, `${JSON.stringify(next, null, 2)}\n`);
  };
  try {
    cpSync(join(ROOT, 'architect-kernels'), sourceDir, { recursive: true });

    // Control: the unmodified fixture builds, so every failure below is caused
    // by the description and not by the fixture copy.
    withDescription(authored);
    assert.ok(buildArchitectArtifacts(catalog, sourceDir)[`generated/architect/${victim}/SKILL.md`]);

    // Each of these is a character YAML gives a structural meaning to. Every
    // one must be refused by name, with the field and the character in the
    // message, rather than written out and discovered by a downstream parser.
    const rejected: Array<[string, RegExp]> = [
      ['Route durable rows: any durable dataset deliverable belongs to tables.', /colon followed by a space/],
      ['- Route durable dataset deliverables to tables.', /leading "-"/],
      ['#1 destination for durable dataset deliverables.', /leading "#"/],
      ['Route durable dataset deliverables to tables:', /trailing ":"/],
      ['Route durable dataset deliverables to tables #canonical', /space followed by "#"/],
    ];
    for (const [description, expected] of rejected) {
      withDescription(description);
      assert.throws(
        () => buildArchitectArtifacts(catalog, sourceDir),
        (error: Error) => {
          assert.match(error.message, expected, `expected ${JSON.stringify(description)} to be refused`);
          assert.match(error.message, new RegExp(`generated/architect/${victim}/SKILL\\.md`));
          assert.match(error.message, /field "description"/);
          assert.match(error.message, new RegExp(JSON.stringify(JSON.stringify(description)).slice(1, -1)));
          return true;
        },
        `expected the build to refuse ${JSON.stringify(description)}`,
      );
    }

    // Prose that is plain-safe still round-trips byte for byte, so the guard
    // rejects ambiguity rather than punctuation.
    const safe = 'Route durable dataset deliverables (tables, columns, rows) to tables.';
    withDescription(safe);
    const artifacts = buildArchitectArtifacts(catalog, sourceDir);
    assert.ok(
      artifacts[`generated/architect/${victim}/SKILL.md`].split('\n').includes(`description: ${safe}`),
    );
  } finally {
    rmSync(fixtureRoot, { recursive: true, force: true });
  }
});
