export interface SkillBlueprint {
  slug: string;
  domain: string;
  description: string;
  related?: string[];
}

function parse(domain: string, rows: string[]): SkillBlueprint[] {
  return rows.map((row) => {
    const [slug, description] = row.split('|');
    return { slug, domain, description };
  });
}

// Original Dreamstate taxonomy. Competitor catalogs informed coverage only;
// names, descriptions, workflow language, and generated instructions are ours.
export const SKILL_BLUEPRINTS: SkillBlueprint[] = [
  ...parse('core', [
    'dreamstate|Route a growth task to the safest Dreamstate primitive before any data is changed.',
    'setup|Install Dreamstate skills, authenticate the client, and verify the connection end to end.',
    'doctor|Diagnose authentication, workspace, scope, billing, provider, and connected-account readiness.',
    'cli|Operate the Dreamstate command line using live help and capability discovery as the authority.',
    'mcp|Discover and use Dreamstate MCP tools with explicit scopes, approvals, and durable verification.',
    'api|Call Dreamstate API resources and typed run intents with idempotency and async result checks.',
    'capabilities|Inspect the workspace-specific capabilities available before selecting an execution path.',
    'usage-and-credits|Estimate, constrain, inspect, and explain Dreamstate credit consumption before paid work.',
    'webhooks|Design and operate signed Dreamstate webhook subscriptions with replay-safe event handling.',
    'audit-log|Trace workspace changes through durable audit records and explain who changed what and when.',
    'safe-bulk-operations|Plan large mutations with previews, explicit caps, approval gates, and recovery checkpoints.',
    'update-skills|Inspect catalog versions and safely update installed Dreamstate skills without overwriting local work.',
    'report-product-feedback|Capture reproducible product feedback with context, evidence, expected behavior, and impact.',
    'run-function-or-routine|Discover and run a saved Dreamstate function or routine with declared inputs and bounded cost.',
  ]),
  ...parse('prospecting', [
    'define-icp|Turn product value and customer evidence into a testable ideal-customer profile.',
    'select-accounts|Build and rank a focused account universe from explicit ICP evidence and exclusions.',
    'map-buying-committee|Identify likely champions, users, blockers, and economic buyers for each account.',
    'source-companies|Source candidate companies from Dreamstate providers while preserving source evidence.',
    'source-people|Find relevant people inside target accounts using role, seniority, and function constraints.',
    'import-and-map-list|Import an external list and map fields into stable Dreamstate columns without data loss.',
    'deduplicate-list|Resolve duplicate people and companies using stable identifiers and reviewable merge rules.',
    'validate-list|Audit list completeness, contactability, fit, freshness, and exclusion compliance before launch.',
    'score-and-tier-leads|Score and tier prospects from explicit fit, timing, relationship, and confidence evidence.',
    'territory-planning|Divide an account universe into fair, explainable territories without duplicate ownership.',
    'total-addressable-market|Estimate a defensible addressable market and preserve the assumptions behind it.',
    'account-research|Produce concise account briefs from verified company, people, event, and relationship evidence.',
    'persona-research|Describe a buying persona through responsibilities, pressures, objections, and desired outcomes.',
    'lead-routing|Route qualified people to the correct owner using explicit territory and priority rules.',
    'build-lookalike-audience|Expand from proven customers into explainable lookalike accounts without copying weak traits.',
    'map-market|Map a market into segments, accounts, relationships, and evidence-backed opportunity areas.',
    'map-account-stakeholders|Build an account stakeholder map that separates influence, authority, use, and relationship strength.',
    'find-account-whitespace|Find defensible expansion whitespace across teams, use cases, products, and uncovered stakeholders.',
    'audit-deal-contact-gaps|Audit active deals for missing champions, users, technical evaluators, and economic buyers.',
    'review-pipeline-account|Review one pipeline account and prioritize the next evidence-backed action.',
    'prepare-sales-call|Prepare a concise sales-call brief from account, person, relationship, signal, and CRM evidence.',
    'conference-prospecting|Build an event prospect list from verified speakers, sponsors, exhibitors, attendees, and themes.',
  ]),
  ...parse('signals', [
    'signal-sourcing|Choose, source, normalize, and verify the timing signals most relevant to a growth motion.',
    'funding-signals|Find and interpret funding events without treating every announcement as purchase intent.',
    'hiring-signals|Use hiring activity to infer changing priorities while preserving role and timing evidence.',
    'job-change-signals|Detect relevant job changes and distinguish new-role timing from routine profile updates.',
    'technology-signals|Use technology adoption and removal evidence to identify fit, displacement, or migration windows.',
    'company-event-signals|Monitor launches, expansions, acquisitions, leadership changes, and other company events.',
    'content-engagement-signals|Turn verified social and content engagement into timely, context-aware follow-up.',
    'competitor-signals|Identify competitor adoption or dissatisfaction without making unsupported displacement claims.',
    'website-intent-signals|Interpret first-party website activity with privacy-safe identity and confidence boundaries.',
    'multi-signal-scoring|Combine several weak signals into an explainable score without double-counting correlated evidence.',
    'product-usage-signals|Use first-party product activity to prioritize expansion, activation, or recovery conversations.',
    'relationship-signals|Surface warm paths from prior interactions, shared history, and trusted introductions.',
    'renewal-signals|Identify renewal windows and risk indicators early enough for a useful customer intervention.',
    'signal-monitoring|Maintain recurring signal coverage with freshness checks, deduplication, and alert thresholds.',
  ]),
  ...parse('tables', [
    'tables|Choose between source, enrichment, formula, action, and workflow primitives for a table job.',
    'build-table|Create a reactive table with a clear row entity, stable identifiers, and declared outputs.',
    'add-source-column|Add a provider-backed source column with validated inputs and inspectable provenance.',
    'enrich-company|Enrich company rows through the smallest provider set that can satisfy the required fields.',
    'enrich-person|Enrich people rows while separating identity, employment, contact, and inferred attributes.',
    'find-and-verify-email|Find and verify work emails through a cost-aware waterfall with confidence labels.',
    'find-phone|Find business phone data through compliant providers and preserve source and confidence metadata.',
    'build-waterfall|Design a provider waterfall that stops on success and exposes cost, confidence, and fallbacks.',
    'formula-and-conditions|Build deterministic formulas and run conditions from explicit fields instead of keyword guesses.',
    'merge-columns|Combine provider outputs into one canonical field while preserving raw evidence and precedence.',
    'run-table-safely|Preview and execute table work with row caps, credit bounds, retries, and partial-result handling.',
    'trace-table-value|Trace a visible table value back through its source, inputs, provider run, and transformation.',
    'sweep-table-errors|Cluster table failures by root cause and repair the highest-impact shared issue first.',
    'optimize-table-cost|Reduce table credit spend without hiding missing data or lowering required confidence.',
    'analyze-table-capacity|Forecast row throughput, provider capacity, completion time, and retry pressure.',
    'normalize-table-data|Normalize names, domains, locations, dates, and identifiers without erasing source values.',
    'table-quality-gate|Block downstream actions until required table fields meet freshness and confidence thresholds.',
    'analyze-table|Reconstruct a table dataflow and explain sources, dependencies, conditions, actions, and risk.',
  ]),
  ...parse('workflows', [
    'workflows|Select, inspect, and safely operate Dreamstate workflows as durable automation graphs.',
    'build-workflow|Design a workflow graph with explicit inputs, branches, retries, approvals, and final outputs.',
    'discover-workflow-actions|Search the live action registry and choose contracts that match the intended outcome.',
    'validate-workflow|Validate graph structure, action inputs, references, scopes, and activation readiness.',
    'run-workflow|Execute a workflow with bounded inputs and verify the durable run rather than the queued response.',
    'trace-workflow|Trace a workflow run across nodes, branches, tool calls, outputs, retries, and failures.',
    'workflow-triggers|Choose and configure schedule, event, webhook, and manual workflow triggers safely.',
    'optimize-workflow|Simplify workflow execution while preserving observable behavior, safety, and recoverability.',
    'snapshot-and-restore-workflow|Plan versioned workflow snapshots and guarded restoration without overwriting newer work.',
    'workflow-error-recovery|Recover partial workflow runs using idempotent retries and explicit compensation steps.',
    'workflow-observability|Define run-level logs, metrics, alerts, and evidence needed to operate automation confidently.',
    'workflow-change-review|Review a proposed workflow diff for contract, cost, data, and activation risk before applying it.',
  ]),
  ...parse('outreach', [
    'outbound|Run a governed outbound motion from sourcing through enrichment, messaging, enrollment, and verification.',
    'write-personalized-opener|Write relevant opening lines from verified prospect evidence without invented familiarity.',
    'build-linkedin-sequence|Build a LinkedIn sequence with connection-state rules, pacing, stop conditions, and approvals.',
    'build-email-sequence|Build an email sequence with deliverability constraints, reply stops, and honest personalization.',
    'build-multichannel-sequence|Coordinate channels around one buyer journey without duplicating pressure or messages.',
    'validate-sequence|Validate custom sequence graph structure, steps, variables, limits, and eligible sender accounts.',
    'launch-campaign|Launch an approved campaign under explicit audience, account, schedule, and volume constraints.',
    'grow-linkedin-network|Build a relevant LinkedIn network with fit checks, safe pacing, and reply-aware follow-up.',
    'classify-replies|Classify reply intent from conversation context and preserve uncertainty for human review.',
    'triage-inbox|Prioritize replies, update intent state, and draft next actions without sending unless authorized.',
    'optimize-campaign|Diagnose campaign performance and change one measurable targeting or sequence variable at a time.',
    'campaign-qa|Audit audience, exclusions, senders, variables, links, pacing, and stop rules before activation.',
    'sender-health|Assess connected-account readiness, pacing pressure, failures, and recovery needs before sending.',
    'reply-routing|Route replies by intent, ownership, urgency, and risk while preserving the full conversation context.',
    'meeting-handoff|Turn positive intent into a clean human handoff with context, ownership, and next-step confirmation.',
    'reengage-prospects|Re-engage prior prospects only when new evidence creates a useful and non-repetitive reason.',
    'campaign-experiment|Design a controlled outreach experiment with one primary variable and a decision rule.',
    'revive-closed-lost|Revisit closed-lost opportunities only when fresh evidence creates a materially different reason.',
    'revive-stale-opportunity|Re-engage a stale opportunity from new account evidence, prior context, and a clear next step.',
    'deliverability-health-check|Audit sending domains, mailboxes, authentication, reputation signals, and campaign pressure.',
    'monitor-deliverability|Monitor deliverability health over time and alert only on actionable changes.',
    'email-deliverability-setup|Plan compliant domain, mailbox, authentication, warmup, and sending-ramp foundations.',
    'linkedin-sending-safety|Operate LinkedIn sending within account health, pacing, acceptance, reply, and restriction signals.',
    'email-compliance|Review outbound email data, identity, consent, suppression, content, and jurisdictional requirements.',
    'analyze-outreach-activity|Analyze outreach activity volume, delivery, acceptance, replies, outcomes, and sender pressure.',
    'compare-sequence-performance|Compare sequences on matched audiences and time windows without hiding sample-size limits.',
    'competitive-displacement-play|Plan a respectful competitor-displacement motion from verified fit and switching evidence.',
    'warm-path-selling|Use trusted relationship evidence to request appropriate introductions without overstating closeness.',
    'inbound-follow-up|Respond to inbound interest with context, speed, qualification, ownership, and useful next steps.',
    'champion-tracking|Track champion movement and relationship continuity across accounts without treating every move as intent.',
    'cold-calling|Plan consent-aware cold calling, research, scripts, objection handling, logging, and stop requirements.',
  ]),
  ...parse('messaging', [
    'messaging-strategy|Choose message angle, evidence, specificity, and call to action for a defined buyer situation.',
    'first-touch-email|Write a concise first-touch email grounded in a specific problem, signal, and credible outcome.',
    'follow-up-email|Write a follow-up that adds new value instead of restating the first message.',
    'reengagement-email|Write a re-engagement email around genuinely new timing, evidence, or product value.',
    'subject-lines|Generate clear subject lines that match the email and avoid manipulative urgency.',
    'personalization-strategy|Select personalization evidence that is relevant, verifiable, and worth mentioning.',
    'executive-vs-practitioner-messaging|Adapt business framing and operational detail to executive and practitioner concerns.',
    'value-proposition|Translate product capabilities into a falsifiable outcome for one buyer and situation.',
    'objection-handling|Respond to objections directly, preserve trust, and stop when the prospect declines.',
    'call-to-action|Choose a low-friction next step proportional to the evidence and relationship.',
    'message-quality-review|Review messaging for relevance, clarity, proof, tone, deliverability, and unsupported claims.',
    'voice-and-tone|Apply a consistent human voice without mimicking a person or fabricating personal experience.',
  ]),
  ...parse('social', [
    'social-content|Route a social content task across ideation, writing, repurposing, scheduling, and analysis.',
    'linkedin-post|Write a LinkedIn post with a clear idea, useful development, and platform-appropriate formatting.',
    'x-post|Write a concise X post or thread that preserves the core argument without empty compression.',
    'content-hooks|Create opening lines that earn attention by establishing tension, value, or specificity honestly.',
    'storytelling-structures|Shape true events into clear narrative movement without inventing scenes or results.',
    'content-calendar|Build a balanced content calendar around audience needs, evidence, formats, and publishing capacity.',
    'repurpose-content|Transform one proven idea across formats while rewriting for each channel rather than copying.',
    'schedule-content|Schedule approved content against account availability, cadence, and campaign conflicts.',
    'publish-content|Publish approved social content and verify the durable platform post and URL.',
    'analyze-content-performance|Interpret content performance using reach, engagement quality, conversion, and context.',
    'thought-leadership|Develop a defensible point of view from expertise, evidence, and useful disagreement.',
    'social-engagement|Plan thoughtful replies and engagement without generic comments or automated relationship claims.',
    'employee-advocacy|Coordinate voluntary employee amplification with original commentary and disclosure boundaries.',
  ]),
  ...parse('seo', [
    'blog-content|Plan, generate, review, and publish useful long-form content through Dreamstate.',
    'keyword-research|Build a keyword set from real audience questions, intent, competition, and product relevance.',
    'track-keyword-rankings|Track keyword movement with stable locations, devices, dates, and comparable snapshots.',
    'analyze-competitor-rankings|Compare ranking coverage and page intent without treating correlation as strategy.',
    'ai-visibility-audit|Measure brand visibility across AI answers and identify defensible improvement opportunities.',
    'citation-gap-analysis|Find sources competitors earn citations from and determine which gaps are worth addressing.',
    'ai-traffic-analysis|Separate AI-referred traffic evidence from crawler activity and unattributed assumptions.',
    'refresh-visibility-measurement|Refresh visibility measurements with the same prompts, providers, locale, and methodology.',
    'content-brief|Create a research-backed content brief with audience, intent, evidence, structure, and differentiation.',
    'content-refresh|Update an existing page from changed facts, decayed coverage, search intent, and performance evidence.',
    'internal-linking|Recommend useful internal links from topical relationships and reader journeys, not keyword stuffing.',
    'schema-markup|Choose and validate structured data that accurately describes visible page content.',
    'technical-seo-audit|Prioritize crawl, indexation, rendering, metadata, and performance issues by observable impact.',
    'answer-engine-content|Structure pages so humans and answer engines can locate clear claims, evidence, and sources.',
    'brand-mention-monitoring|Monitor brand mentions across search and AI surfaces with sentiment and source context.',
  ]),
  ...parse('crm', [
    'crm|Route CRM work across field design, synchronization, automation, health, ownership, and reporting.',
    'configure-crm-fields|Design CRM fields with clear ownership, types, allowed values, and lifecycle semantics.',
    'sync-contact-to-crm|Synchronize a qualified contact with identity matching, field precedence, and retry safety.',
    'configure-crm-automation|Design CRM automation with explicit triggers, idempotency, ownership, and failure handling.',
    'crm-health-check|Audit duplicates, stale fields, broken ownership, sync failures, and lifecycle inconsistencies.',
    'route-and-assign-leads|Assign leads using explicit territory, capacity, account ownership, and escalation rules.',
    'lifecycle-management|Define and enforce lifecycle stages from durable customer events rather than activity guesses.',
    'pipeline-hygiene|Find stale, contradictory, or ownerless opportunities and propose reviewable corrections.',
    'crm-deduplication|Merge CRM duplicates with stable identity evidence, field precedence, and reversible review.',
    'revenue-reporting|Build revenue reports from declared definitions, time windows, attribution limits, and source records.',
    'customer-expansion|Identify expansion opportunities from product value, account context, and relationship evidence.',
    'churn-risk|Identify churn risk from explicit customer signals and route intervention without overstating certainty.',
  ]),
  ...parse('ads', [
    'linkedin-ads|Route LinkedIn advertising work across audience, campaign, creative, budget, measurement, and optimization.',
    'linkedin-ads-abm-strategy|Design an account-based LinkedIn advertising strategy aligned to sales coverage and buying stages.',
    'linkedin-ads-audiences|Define LinkedIn advertising audiences with exclusions, size checks, privacy, and refresh rules.',
    'linkedin-ads-campaign-setup|Plan LinkedIn campaign objectives, structure, placements, schedule, and activation safeguards.',
    'linkedin-ads-bidding|Choose bidding and budget controls from objective, audience, learning, and downside constraints.',
    'linkedin-ads-copy|Write clear LinkedIn ad copy that matches the offer, landing experience, and audience evidence.',
    'linkedin-ads-creative|Develop LinkedIn ad creative concepts with message hierarchy, format fit, and review criteria.',
    'linkedin-ads-measurement|Define LinkedIn ad measurement, attribution boundaries, conversion events, and decision windows.',
    'linkedin-ads-optimization|Optimize LinkedIn advertising from matched evidence without reacting to noisy early results.',
    'linkedin-ads-outbound-sync|Coordinate advertising and outbound touches without duplicate pressure or attribution claims.',
  ]),
  ...parse('automation', [
    'external-automation|Integrate Dreamstate with external automation tools through APIs and signed webhooks.',
    'n8n-interoperability|Connect n8n to Dreamstate through generic API and webhook contracts without managing n8n itself.',
    'automation-error-handling|Design external automation retries, dead letters, idempotency, alerts, and manual recovery.',
  ]),
];
